config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'cars#index'

  post 'cars/search' => 'cars#search', as: 'search_cars'
  get 'users/:id' => 'dashboards#show', as: 'user'
  get 'dashboard' => 'dashboards#dashboard', as: 'dashboard'

  resources :bookings, only: [:show] do
    resources :reviews, only: [:create]
  end


  resources :cars do
    resources :bookings, except: [:show]

  end
mount Attachinary::Engine => "/attachinary" # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="container">
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.25), rgba(0,0,0,0.25)), url('https://res.cloudinary.com/ders-cloud/image/upload/v1487609876/ryan-hefner-190737_dbdfmh.jpg');">
      <div class="banner-content">
        <h1>Welcome to Classic Cars</h1>
        <p>Browse from a selection of 1000+ vintage cars and find the one you love. <br>Are you ready to get behind the wheel?</p>
        <form action="#" class="form-inline">
          <input type="text" class="form-control" placeholder="zipcode">
          <input type="text" class="form-control" placeholder="start date">
          <input type="text" class="form-control" placeholder="end date">
          <select name="" id="" class="form-control">
            <option value="1">all</option>
            <option value="2">50's</option>
            <option value="3">60's</option>
            <option value="4">70's</option>
          </select>
          <input type="submit" class="btn btn-primary" value="Search">
        </form>
      </div>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible"  style="padding-top: 15px"role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <!-- <div id="footer"> -->
      <div class="container">
        <div class="row">
          <div class="col-xs-4">
            <ul class="list-inline">

              <li><%= link_to 'Home', cars_path %></li> |
              <li><%= link_to 'Dashboard', dashboard_path %></li>

            </ul>
          </div>
          <div class="col-xs-8 text-right">
            <p>Made with love @ LeWagon</p>
          </div>
        </div>
      </div>
    <!-- </div> -->
</footer>

app/views/shared/_navbar.html.erb
<!-- <div class="navbar-overlay overlay-fixed"></div> -->

<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag("cc_icon.png") %>
  </a>
  <!-- Title -->
  <h3><%= link_to "Classic Cars", cars_path, class: "navbar-wagon-link navbar-wagon-padding-right"%></h3>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <% if current_user %>
        <%= current_user.name %>
        <%end%>
        <!-- facebook avatar SHOULD USE A HELPER FOR THIS-->
        <%= image_tag avatar_url(current_user), class: "avatar avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Home", "/" %></li>
          <li>
            <!-- login/logout NEEDS LOGOUT TEXT TO TOGGLE & SHOULD USE HELPER -->
            <% if user_signed_in? %>
              <%= link_to "Logout", destroy_user_session_path, {class: "navbar-wagon-item navbar-wagon-link", method: :delete}%>
            <%else%>
              <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"%>
            <%end%>
          </li>
        </ul>
      </div>
    </div>

  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Dashboard", dashboard_path %></li>
        <li><%= link_to "Home", "/" %></li>
        <li>
          <!-- login/logout NEEDS LOGOUT TEXT TO TOGGLE & SHOULD USE HELPER -->
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, {class: "navbar-wagon-item navbar-wagon-link", method: :delete}%>
          <%else%>
            <%= link_to "Login", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"%>
          <%end%>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search_banner.html.erb
    <div class="banner" >
      <div class="banner-content" >
        <br>
        <div class="row">
          <div class="col-xs-12">
            <h1>Classic Cars</h1>
          </div>
          <div class="col-xs-12">
            <%= form_tag search_cars_path do %>
              <div class="highlight">
                <form action="#" class="form-inline transparent-input">
                  <input id="searchTextField" style="width: 212.5px;" type="text" name="location" class="transparent-input" placeholder="Search car by city, country">
                  <input type="text" style="width: 212.5px;" name="query" class=" transparent-input" placeholder="Search car by model, brand">
                  <input type="submit" style="width: 100px;" class="btn btn-primary" value="Search">
                </form>
              </div>
            <%end%>
          </div>
        </div>
      </div>
      <br><br><br>

    </div>
<% content_for(:after_js) do %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_AUTOCOMPLETE_KEY']}&libraries=places"%>
  <script>
  var defaultBounds = new google.maps.LatLngBounds(
  new google.maps.LatLng(-33.8902, 151.1759),
  new google.maps.LatLng(-33.8474, 151.2631));

  var input = document.getElementById('searchTextField');
  var options = {
    bounds: defaultBounds,
    types: ['establishment']
  };

  autocomplete = new google.maps.places.Autocomplete(input, options);
  </script>
<%end%>