config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'cars#index'

  post 'cars/search' => 'cars#search', as: 'search_cars'
  get 'users/:id' => 'dashboards#show', as: 'user'
  get 'dashboard' => 'dashboards#dashboard', as: 'dashboard'

  resources :bookings, only: [:show] do
    resources :reviews, only: [:create]
  end


  resources :cars do
    resources :bookings, except: [:show]

  end
mount Attachinary::Engine => "/attachinary" # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!, only: [ :dashboard ]

  def show
    @user = User.find(params[:id])
  end

  def dashboard
    # @bookings = Booking.all
    @bookings = current_user.bookings
    # @bookings = current_user.(Booking.all)
    @cars = current_user.cars
    # @owners = []
    # current_user.bookings.each do |booking|
    # @owners << booking.car.user # consider deleting
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/dashboard.html.erb
<div class="wrapper-grey">
  <div class="container-wrap light-grey-background">
    <div>
    <br>
      <%= image_tag avatar_url(current_user), class: "avatar avatar-dash" %>
    </div>
    <div class="">
      <hr>
      <h3>Your Cars</h3>
      <hr>
      <div class="row">
        <div class="col-xs-12 col-sm-6">
          <p>  <% @cars.each do |car| %>
              <%= link_to "#{car.brand} #{car.model}", car_path(car),class: "btn btn-primary" %>
            <% end %>
          </p>
      <%= link_to "Add new car", new_car_path, class: "btn btn-lg btn-primary" %>
        </div>
      </div>
      <hr>

    <!-- added list to show bookings on user's cars from other cars, copied frontend code from bookings of the user (the two paragraphs below), and made slight modification to erb -->
      <h3>Bookings on your cars</h3>

      <% current_user.cars.each do |car| %>
        <% car.bookings.each do |booking| %>
          <div class="row">
            <div class="col-xs-12 col-sm-6">
            <br><br>
              <ul>
                <li>Car: <%= link_to "#{booking.car.brand} #{booking.car.model}", car_path(booking.car) %></li>
                <li>Customer name: <%= booking.car.user.name %></li>
                <li>Customer email: <%= link_to booking.user.email, user_path(booking.user) %></li>
                <li>Start Date: <%= booking.start_date %></li>
                <li>End Date: <%= booking.end_date %></li>
              </ul>

              <% if booking.pending %>
                <div class="text-center">
                  <%= link_to "Accept booking", car_booking_path(booking.car, booking), class: "btn btn-lg btn-primary", method: :patch %>
                  <%= link_to "Refuse booking", car_booking_path(booking.car, booking), { class: "btn btn-lg btn-primary", method: :delete } %>
                </div>
              <% end %>
            </div>
            <div class="col-xs-12 col-sm-6">
              <section id="content-dash">
              <%= link_to "", car_path(car), class: "card-link"%>

              <h4><%=car.brand%> <%=car.model%></h4>



              <div id="head-dash" style="background: url(<%= car_image_url?(car)%>);"></div>


            </section>



              <!-- <div class="card card-dash" style="url('<%= car_image_url?(booking.car) %>');">
                <div class="card-location"><%#= "booking.car.location" %>
                </div>
                <div class="card-description">
                  <h2><%= booking.car.brand %> <%= booking.car.model %>
                  </h2>
                </div>
                <%#= link_to "", car_path(booking.car), class: "card-link" %>
              </div> -->
            </div>
          </div>
        <% end %>
      <% end %>
      <h3>Your Bookings History</h3>
      <hr>
      <% @bookings.each do |booking| %>
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <ul>
              <li>Car: <%= link_to "#{booking.car.brand} #{booking.car.model}", car_path(booking.car) %></li>
              <li>Owner name: <%= booking.car.user.name %></li>
              <li>Owner email: <%= link_to booking.car.user.email, user_path(booking.car.user) %></li>
              <li>Start Date: <%= booking.start_date %></li>
              <li>End Date: <%= booking.end_date %></li>
              <% if Time.now > booking.end_date %>
              <p>
                <%= link_to "Add review", car_path(booking.car), class: "btn btn-primary" %>
              </p>
              <% end %>
            </ul>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= car_image_url?(booking.car) %>');">
              <div class="card-location">
                <%= "booking.car.location" %>
              </div>
              <div class="card-description">
                <h2><%= booking.car.brand %> <%= booking.car.model %></h2>
              </div>
              <%= link_to "", car_path(booking.car), class: "card-link" %>
            </div>
          </div>
        </div>
      <% end %>
    <!-- </div> -->
  </div>
</div>

app/views/dashboards/show.html.erb
name <%= @user.name %>
<br>
email <%= @user.email %>
<br>
cars <% @user.cars.each do |car| %>
<%= car.brand %>
<%= car.model %>
<br>
<%end%>