config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'cars#index'

  post 'cars/search' => 'cars#search', as: 'search_cars'
  get 'users/:id' => 'dashboards#show', as: 'user'
  get 'dashboard' => 'dashboards#dashboard', as: 'dashboard'

  resources :bookings, only: [:show] do
    resources :reviews, only: [:create]
  end


  resources :cars do
    resources :bookings, except: [:show]

  end
mount Attachinary::Engine => "/attachinary" # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  has_attachments :car_image, maximum: 5
  belongs_to :user
  has_many :users, through: :bookings
  has_many :bookings, dependent: :destroy

  has_many :reviews, through: :bookings, dependent: :destroy

  validates :model, presence: true
  validates :brand, presence: true
  validates :location, presence: true
  validates :price, presence: true
  validates :user, presence: true

  geocoded_by :location
  before_validation :geocode, if: :location_changed?

  include PgSearch
   pg_search_scope :search_by_model_and_brand, :against => [:model, :brand],
                   :using => {:tsearch => {:prefix => true}}
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [ :index , :show, :search ]

  def search
    @cars_l = []
    @cars_q = Car.search_by_model_and_brand(params[:query])
    @cars_l += Car.near(params[:location], 20)
    if params[:location].blank?
      @cars = @cars_q
    elsif params[:query].blank?
      @cars = @cars_l
    else
      @cars = @cars_l.select { |elem| @cars_q.include?(elem) }
    end
    @hash = cars_location_marker(@cars)
    render :search
  end

  def index
    @cars = Car.all
  end

  def show
    @booking_review = Booking.where(user: current_user, car: @car)[0]
    @booking_blank = Booking.new
    @review = Review.new
    @cars = [@car]
    @hash = cars_location_marker(@cars)
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def update
    @car.update(car_params)
    if @car.save
      redirect_to car_path(@car)
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to dashboard_path
  end

  private

  def cars_location_marker(cars)
      Gmaps4rails.build_markers(cars) do |car, marker|
      marker.lat car.latitude
      marker.lng car.longitude
    end
  end

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:brand, :model, :description, :location, :price, car_image: [])
  end
end

app/helpers/cars_helper.rb
module CarsHelper

  def car_image?
    if !@car.car_image.empty?
      @car.car_image.first.path
    else
      "v1487707587/tdamefabs3mqikk9hrpr.jpg"
    end
  end

  def car_image_url?(car)
    if !car.car_image.empty?
      cl_image_path(car.car_image.first.path, width: 600, height: 400, crop: :fill)
    else
      "https://img.clipartfox.com/ee10ada04750133968c37e94c30c38b4_-clip-art-vintage-cars-and-classic-car-bw-clipart_1575-1260.jpeg"
    end
  end
end

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <%= f.input :brand, placeholder: "Enter brand"  %>
  <%= f.input :model, placeholder: "Enter model"  %>
  <%= f.input :location, placeholder: "Enter city" %>
  <%= f.input :description, placeholder: "Describe car condition" %>
  <%= f.input :price, placeholder: "Enter daily rate", label: 'Rate (€)' %>
  <%= f.input :car_image, as: :attachinary %>
  <%= f.submit :submit %>
<% end %>

<% content_for(:after_js) do %>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_AUTOCOMPLETE_KEY']}&libraries=places"%>
  <script>
  var defaultBounds = new google.maps.LatLngBounds(
  new google.maps.LatLng(-33.8902, 151.1759),
  new google.maps.LatLng(-33.8474, 151.2631));

  var input = document.getElementById('car_location');
  var options = {
    bounds: defaultBounds,
    types: ['establishment']
  };

  autocomplete = new google.maps.places.Autocomplete(input, options);
  </script>
<%end%>

app/views/cars/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Edit Car</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<%= render 'shared/search_banner' %>
<div class="wrapper-grey">
  <div class="container-wrap text-center light-grey-background">
    <h1>Car Listings</h1>


    <div class="row">
      <div class="col-xs-12">  <!-- col-sm-offset-2 col-sm-8 -->
        <% @cars.sample(21).each do |car| %>
          <div class="col-xs-12 col-sm-4">
            <section id="content">
              <%= link_to "", car_path(car), class: "card-link"%>

              <h4><%=car.brand%> <%=car.model%></h4>

              <div id="profile_pic" style="background: url(<%= avatar_url(car.user)%>);">
              </div>

              <div id="head" style="background: url(<%= car_image_url?(car)%>);"></div>

              <p>
                <i class="fa fa-user-o" aria-hidden="true"></i>  <%=car.user.name%>
              </p>
              <p>
                <i class="fa fa-money" aria-hidden="true"></i>  €<%=car.price%>
              </p>
              <p>
                <i class="fa fa-globe" aria-hidden="true"></i>  <%=car.location%>
              </p>
              <p><i class="fa fa-star" style="color: #ffb400"></i>
                <i class="fa fa-star" style="color: #ffb400"></i>
                <i class="fa fa-star" style="color: #ffb400"></i>
                <i class="fa fa-star" style="color: #ffb400"></i>
                <i class="fa fa-star" style="color: #cacccd"></i>
              </p>



            </section>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

<script>
  var input = document.getElementById('searchTextField');
  var options = {
    bounds: defaultBounds,
    types: ['establishment']
  };

  autocomplete = new google.maps.places.Autocomplete(input, options);
</script>

app/views/cars/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Car</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/cars/search.html.erb
<h1>Search Results</h1>
<div class="row">
  <div class="map-body">
    <div class="col-xs-12 col-sm-5">
      <div id="map" class="map-fixed" style="margin: 0;
      padding: 0; width: 500px;">
      </div>
    </div>

    <div class="col-xs-12 col-sm-6">
      <% @cars.each do |car| %>
        <div class="product">
          <div class='product-upvote'>
            <div class="product-arrow"></div>
            <div class='product-count'>95</div>
          </div>
      <%= link_to "", car_path(car), class: "card-link" %>
      <%= image_tag car_image_url?(car), {class: "product-image", style: "background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2));"}%>


      <div class='product-body'>
        <h3><%= car.brand %> <%= car.model %></h3>
        <p><%= car.location %></p>
      </div>
      <div class='product-body'>
        <%= image_tag avatar_url(car.user), class: "avatar-search" %>
        <%= car.user.name %>
        <ul class="list-inline product-controls product-controls-hidden hidden-sm hidden-xs">
          <li><a href=""><i class="fa fa-heart"></i></a></li>
          <li><a href=""><i class="fa fa-share"></i></a></li>
          <li><a href=""><i class="fa fa-star"></i></a></li>
        </ul>
      </div>
    </div>
    <%end%>
  </div>
  </div>
  </div>




<% content_for(:after_js) do %>
    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>

  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<%end%>

app/views/cars/show.html.erb
<div class="wrapper-grey">
  <div class="container-wrap light-grey-background" style="width:70%">
    <div class="text-center">
      <!-- <div class="container"> -->
        <div class="row">
              <h1><%= @car.brand %> <%= @car.model %></h1>
          <div class="col-xs-12 col-sm-offset-2 col-sm-8 ">
            <div class="text-center">
              <!-- <div class="slickbox"> -->
                <% @car.car_image.each do |img| %>
                  <div><%= cl_image_tag img.path, class: "avatar-car" %>
                  </div>
                <% end %>
              <!-- </div> -->
              <p>
                <%= @car.location %>
              </p>
              <i class="fa fa-star" style="color: #ffb400"></i>
              <i class="fa fa-star" style="color: #ffb400"></i>
              <i class="fa fa-star" style="color: #ffb400"></i>
              <i class="fa fa-star" style="color: #ffb400"></i>
              <i class="fa fa-star" style="color: #cacccd"></i>
            </div>
          </div>

        <!-- </div> -->
        <div class="row">
          <div class="col-xs-12 col-sm-10 col-sm-offset-1">
            <h2>About the Car</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
            </p>
            <% if current_user == @car.user %>
              <%= link_to "Edit car description", edit_car_path(@car), class: "btn btn-primary" %>
              <%= link_to "Delete listing", car_path(@car), { method: :destroy, class: "btn btn-danger" } %>
            <%end%>
            <hr>
            <div class="row" id="flat-data">
              <div class="col-xs-12 col-sm-2">
                The Specs
              </div>
              <div class="col-xs-12 col-sm-4">
                <ul class="list-unstyled">
                  <li>Owner: <strong><%= @car.user.email %></strong></li>
                  <li>Model: <strong><%= @car.brand %> <%= @car.model %></strong></li>
                </ul>
              </div>
              <div class="col-xs-12 col-sm-4">
                <ul class="list-unstyled">
                  <li>Condition: <strong><%= @car.description %></strong></li>
                  <li>Location: <strong><%= @car.location %></strong></li>
                  <li>Daily rate: <strong> <%= @car.price %> €</strong></li>
                </ul>
              </div>
            </div>
            <hr>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-6">
            <div id="map" style="width: 100%; height: 300px;">
            </div>
          </div>
          <div class="col-xs-12 col-sm-6 ">
            <div class="padding">
              <% if @car.user != current_user %>
                <!-- <div class="col-xs-4 col-sm-3 col-sm-offset-4"> -->
                  <h1>New Booking</h1>
                  <%= simple_form_for [@car, @booking_blank] do |f| %>
                    <%= f.input :start_date, as: :string, input_html: {class: "datepicker"}, placeholder: "from"  %>
                    <%= f.input :end_date, as: :string, input_html: {class: "datepicker"}, placeholder: "to"  %>
                    <%= f.submit "Book your ride", class: "btn btn-primary" %>
                  <% end %>
                <!-- </div> -->
              <%end%>
            </div>
          </div>

        </div>
        <hr>
        <%# if !@car.reviews.empty? %>
          <div class="row">
            <div class="col-xs-12 col-sm-10 col-sm-offset-1">
              <h2>
                <%= pluralize @car.reviews.size, "review" %>
              </h2>
              <div id="reviews">
                <% if @car.reviews.blank? %>
                  <p>Be first to leave a review for the <%= @car.brand%> <%=@car.model%></p>
                <% else %>
                  <% @car.reviews.each do |review| %>
                      <%= render 'reviews/show', review: review %>
                  <%end%>
                <%end%>
              </div>
              <!-- can only see add review form if logged in-->
              <% if @booking_review%>
                <%= render 'reviews/formreview', booking: @booking_review, review: @review %>
              <% else %>
              <p>Please place a booking before writing a review</p>
              <%end%>
            </div>
          </div>
        <%#end%>
      <!-- </div> -->
      <hr>
    </div>
  </div>
</div>
<% content_for(:after_js) do %>
  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <script>
    $(document).ready(function() {
      var handler = Gmaps.build('Google');
      handler.buildMap({ internal: { id: 'map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>